name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 16.171.28.204
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd Cloud_project
          git pull
          pm2 restart app